# Generated by Django 4.0.4 on 2022-05-12 19:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sparrow_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-datepost']},
        ),
        migrations.RemoveField(
            model_name='users',
            name='lastlog',
        ),
        migrations.AlterField(
            model_name='message',
            name='datepost',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='users',
            name='regdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
