# Generated by Django 4.0.4 on 2022-05-13 04:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sparrow_app', '0002_alter_message_options_remove_users_lastlog_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='list_follow',
            options={'verbose_name': 'Lista de Seguidores', 'verbose_name_plural': 'Listas de Seguidores'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-datepost'], 'verbose_name': 'Mensaje', 'verbose_name_plural': 'Mensajes'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='list_follow',
            name='follow_date',
            field=models.DateTimeField(verbose_name='Fecha de seguimiento'),
        ),
        migrations.AlterField(
            model_name='list_follow',
            name='id_friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Siguiendo', to='sparrow_app.users', verbose_name='Id de Seguidor'),
        ),
        migrations.AlterField(
            model_name='list_follow',
            name='id_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Seguidor', to='sparrow_app.users', verbose_name='Id de Usuario'),
        ),
        migrations.AlterField(
            model_name='message',
            name='Image',
            field=models.ImageField(upload_to='', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='message',
            name='datepost',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de posteo'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sparrow_app.users', verbose_name='ID de usuario'),
        ),
        migrations.AlterField(
            model_name='users',
            name='profilepic',
            field=models.ImageField(upload_to='', verbose_name='Imagen de perfil'),
        ),
        migrations.AlterField(
            model_name='users',
            name='regdate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro'),
        ),
    ]
