# Generated by Django 4.0.4 on 2022-05-16 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparrow_app', '0004_user_profile_alter_list_follow_id_friend_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='fullname',
        ),
    ]
