# Generated by Django 4.0.4 on 2022-05-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sparrow_app', '0005_remove_user_profile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='username',
            field=models.CharField(default=None, max_length=15, verbose_name='Sobrenombre'),
            preserve_default=False,
        ),
    ]
