# Generated by Django 4.0.4 on 2022-06-15 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sparrow_app', '0009_alter_user_profile_bgcolor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='profilepic',
            field=models.ImageField(blank=True, null=True, upload_to='media/profiles/', verbose_name='Imagen de perfil'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='username',
            field=models.CharField(max_length=15, verbose_name='Nombre a Mostrar'),
        ),
    ]
