# Generated by Django 4.0.4 on 2022-06-15 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sparrow_app', '0010_alter_message_user_id_alter_user_profile_profilepic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_profile',
            old_name='username',
            new_name='watchname',
        ),
    ]
